version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "jurijzahn8019"
    default_labels:
      - "dependabot :dart:"
    version_requirement_updates: "increase_versions"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

